export default {
  validUserObject: {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimy@andela.com',
    password: 'h-forsetti-2019'
  },
  invalidData: [{
    firstname: '',
    lastname: 'Ogundimu',
    email: 'd.ogundimy1@andela.com',
    password: 'h-forsetti-2019'
  }, {
    firstname: 'David',
    lastname: '',
    email: 'd.ogundimy2@andela.com',
    password: 'h-forsetti-2019'
  }, {
    firstname: 'David',
    lastname: 'Ogundimu',
    email: '',
    password: 'h-forsetti-2019'
  }, {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimy3@andela.com',
    password: ''
  }, {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimy@andela.com',
    password: 'h-forsetti-2019'
  }, {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimyandela.com',
    password: 'h-forsetti-2019'
  }, {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimy12@andela.com',
    password: 'pass12'
  }, {
    firstname: 'David"',
    lastname: 'Ogundimu',
    email: 'd.ogundimy123@andela.com',
    password: 'password'
  }],
};
